[build]
    incremental = true

[workspace]
    members = [
        "browser",
        "tl2wasm",
    ]

    [workspace.package]
        authors = ["Maxine Zick <maxine@pnk.dev>"]
        version = "0.1.0"
        edition = "2024"
        keywords = ["bitgrid", "browser", "teal", "wasm", "javascript"]
        categories = ["wasm", "gui", "api-bindings", "compilers", "embedded"]
        resolver = "3"

    [workspace.dependencies.tl2wasm]
        name = "tl2wasm"
        version = "0.1.0"
        path = "tl2wasm"

[alias]
    run = "run -p browser"
    build = "build -p browser"

